[0m11:35:39.710303 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ffa5d561060>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ffa5b299fc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ffa5b299ff0>]}


============================== 11:35:39.726247 | f4183913-7b5a-492c-b203-f8874ef51d1a ==============================
[0m11:35:39.726247 [info ] [MainThread]: Running with dbt=1.7.3
[0m11:35:39.727993 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/robgriffin247/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m11:35:39.730081 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/home/robgriffin247/.dbt')}
[0m11:35:39.731410 [info ] [MainThread]: Creating dbt configuration folder at 
[0m11:35:55.864134 [error] [MainThread]: Encountered an error:

[0m11:35:55.868990 [error] [MainThread]: Traceback (most recent call last):
  File "/home/robgriffin247/.cache/pypoetry/virtualenvs/swapi-dataplatform-DEMA7jFj-py3.10/lib/python3.10/site-packages/dbt/cli/requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/robgriffin247/.cache/pypoetry/virtualenvs/swapi-dataplatform-DEMA7jFj-py3.10/lib/python3.10/site-packages/dbt/cli/requires.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/home/robgriffin247/.cache/pypoetry/virtualenvs/swapi-dataplatform-DEMA7jFj-py3.10/lib/python3.10/site-packages/dbt/cli/main.py", line 515, in init
    results = task.run()
  File "/home/robgriffin247/.cache/pypoetry/virtualenvs/swapi-dataplatform-DEMA7jFj-py3.10/lib/python3.10/site-packages/dbt/task/init.py", line 322, in run
    project_name = self.get_valid_project_name()
  File "/home/robgriffin247/.cache/pypoetry/virtualenvs/swapi-dataplatform-DEMA7jFj-py3.10/lib/python3.10/site-packages/dbt/task/init.py", line 276, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
  File "/home/robgriffin247/.cache/pypoetry/virtualenvs/swapi-dataplatform-DEMA7jFj-py3.10/lib/python3.10/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/home/robgriffin247/.cache/pypoetry/virtualenvs/swapi-dataplatform-DEMA7jFj-py3.10/lib/python3.10/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m11:35:55.879624 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 16.17254, "process_user_time": 1.962226, "process_kernel_time": 0.30544, "process_mem_max_rss": "100672", "process_out_blocks": "21160", "command_success": false, "process_in_blocks": "0"}
[0m11:35:55.884210 [debug] [MainThread]: Command `dbt init` failed at 11:35:55.883605 after 16.18 seconds
[0m11:35:55.887481 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ffa5d561060>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ffa5b32f250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ffa5b32f610>]}
[0m11:35:55.890842 [debug] [MainThread]: Flushing usage events
[0m11:36:28.726160 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc7c92ef670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc7c70a3460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc7c70a3400>]}


============================== 11:36:28.730363 | a676a135-e4d9-4db0-9080-7cc2ae53f947 ==============================
[0m11:36:28.730363 [info ] [MainThread]: Running with dbt=1.7.3
[0m11:36:28.732338 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/robgriffin247/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:36:45.663923 [debug] [MainThread]: Starter project path: /home/robgriffin247/.cache/pypoetry/virtualenvs/swapi-dataplatform-DEMA7jFj-py3.10/lib/python3.10/site-packages/dbt/include/starter_project
[0m11:36:45.854286 [info ] [MainThread]: 
Your new dbt project "swapi_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:36:45.855500 [info ] [MainThread]: Setting up your profile.
[0m11:38:43.958316 [info ] [MainThread]: Profile swapi_dbt written to /home/robgriffin247/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m11:38:43.964580 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 135.24577, "process_user_time": 1.885488, "process_kernel_time": 0.744768, "process_mem_max_rss": "187596", "process_out_blocks": "360", "process_in_blocks": "0"}
[0m11:38:43.968874 [debug] [MainThread]: Command `dbt init` succeeded at 11:38:43.968497 after 135.25 seconds
[0m11:38:43.971974 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc7c92ef670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc7cb4231f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc7c70a36d0>]}
[0m11:38:43.974817 [debug] [MainThread]: Flushing usage events
[0m13:20:25.258484 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff684e993f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff6857dbd90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff682bc0700>]}


============================== 13:20:25.263089 | ce263791-03cb-4d98-9c99-fa1bcffb6c89 ==============================
[0m13:20:25.263089 [info ] [MainThread]: Running with dbt=1.7.3
[0m13:20:25.264484 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/robgriffin247/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:20:25.266210 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /mnt/c/Users/robgri/Documents/github/personal/swapi_dataplatform/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:20:25.267997 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.0708728, "process_user_time": 1.518113, "process_kernel_time": 0.162655, "process_mem_max_rss": "97372", "process_in_blocks": "23336", "process_out_blocks": "24", "command_success": false}
[0m13:20:25.269635 [debug] [MainThread]: Command `dbt run` failed at 13:20:25.269469 after 0.07 seconds
[0m13:20:25.270933 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff684e993f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff682bc3ac0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff682bc2950>]}
[0m13:20:25.272286 [debug] [MainThread]: Flushing usage events
[0m13:20:47.789851 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f96b11653f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f96b1aa7d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f96aef01c30>]}


============================== 13:20:47.793784 | c2e1d6a0-b464-4229-ab85-2b2e0b668c88 ==============================
[0m13:20:47.793784 [info ] [MainThread]: Running with dbt=1.7.3
[0m13:20:47.795048 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/robgriffin247/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt build', 'send_anonymous_usage_stats': 'True'}
[0m13:20:47.796440 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /mnt/c/Users/robgri/Documents/github/personal/swapi_dataplatform/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:20:47.798021 [debug] [MainThread]: Resource report: {"command_name": "build", "command_wall_clock_time": 0.07990264, "process_user_time": 1.455449, "process_kernel_time": 0.036846, "process_mem_max_rss": "97320", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m13:20:47.799565 [debug] [MainThread]: Command `dbt build` failed at 13:20:47.799388 after 0.08 seconds
[0m13:20:47.800741 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f96b11653f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f96aef00ac0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f96aef031f0>]}
[0m13:20:47.802141 [debug] [MainThread]: Flushing usage events
[0m13:21:32.678658 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6600eb93f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f66017fbd90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f65febe8700>]}


============================== 13:21:32.682133 | 0c5f7b18-a1d8-4f30-a6f5-049ef9417f8b ==============================
[0m13:21:32.682133 [info ] [MainThread]: Running with dbt=1.7.3
[0m13:21:32.683754 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/robgriffin247/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m13:21:32.685695 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /mnt/c/Users/robgri/Documents/github/personal/swapi_dataplatform/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:21:32.687587 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.06786726, "process_user_time": 1.482718, "process_kernel_time": 0.037301, "process_mem_max_rss": "97356", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m13:21:32.689308 [debug] [MainThread]: Command `dbt run` failed at 13:21:32.689136 after 0.07 seconds
[0m13:21:32.690929 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6600eb93f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f65febebac0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f65febea950>]}
[0m13:21:32.692472 [debug] [MainThread]: Flushing usage events
[0m13:21:37.873158 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3f88d3f430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3f89683d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3f86ad9f30>]}


============================== 13:21:37.877020 | 5663b2db-068b-48d5-bd73-bedec7a5f09a ==============================
[0m13:21:37.877020 [info ] [MainThread]: Running with dbt=1.7.3
[0m13:21:37.878484 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/robgriffin247/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt test', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:21:37.879851 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /mnt/c/Users/robgri/Documents/github/personal/swapi_dataplatform/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:21:37.881442 [debug] [MainThread]: Resource report: {"command_name": "test", "command_wall_clock_time": 0.07111054, "process_user_time": 1.438271, "process_kernel_time": 0.054965, "process_mem_max_rss": "97328", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m13:21:37.882750 [debug] [MainThread]: Command `dbt test` failed at 13:21:37.882589 after 0.07 seconds
[0m13:21:37.883667 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3f88d3f430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3f86adaf20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3f86ada7d0>]}
[0m13:21:37.884663 [debug] [MainThread]: Flushing usage events
[0m14:43:44.436900 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb00f02b430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb00f983d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb00cd11f30>]}


============================== 14:43:44.441376 | 74cfadd5-6947-4eb9-9d7b-03611edde5ac ==============================
[0m14:43:44.441376 [info ] [MainThread]: Running with dbt=1.7.3
[0m14:43:44.443062 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/robgriffin247/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt test', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:43:44.444589 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /mnt/c/Users/robgri/Documents/github/personal/swapi_dataplatform/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:43:44.446576 [debug] [MainThread]: Resource report: {"command_name": "test", "command_wall_clock_time": 0.11135576, "process_user_time": 3.425605, "process_kernel_time": 0.23463, "process_mem_max_rss": "97204", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m14:43:44.447861 [debug] [MainThread]: Command `dbt test` failed at 14:43:44.447673 after 0.11 seconds
[0m14:43:44.449180 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb00f02b430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb00cd12f20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb00cd127d0>]}
[0m14:43:44.450273 [debug] [MainThread]: Flushing usage events
